import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {openStore,appendObservation,archiveDocument,readDashboard,observationHistory,appendTerritory,claimSource,finishSource,seedReferences} from '../src/lib/omni/store.mjs';
import {parseReliefWeb,syncSources} from '../src/lib/omni/collect.mjs';
import {sources,topics} from '../src/lib/omni/catalog.mjs';
const base={sourceId:'who',externalId:'bulletin',domain:'pandemic',topic:'hantavirus',title:'Bilan',url:'https://www.who.int/example',occurredAt:'2026-05-01T00:00:00Z',publishedAt:'2026-05-03T12:00:00Z',status:'reported',metrics:{confirmed:12}};
const first='2026-05-04T00:00:00.000Z',later='2026-05-06T00:00:00.000Z';
const snapshot={type:'FeatureCollection',metadata:{topic:'ukraine',datasetId:'test-fixture',publisher:'TEST ONLY',sourceUrl:'https://example.com/test',license:'CC0 — synthetic test fixture',validAt:'2026-05-01T00:00:00Z'},features:[{type:'Feature',geometry:{type:'Polygon',coordinates:[[[30,48],[31,48],[31,49],[30,48]]]},properties:{id:'a',actor:'Test actor',status:'controlled'}}]};
function memory(t){const db=openStore(':memory:');t.after(()=>db.close());return db;}
test('document metadata archive deduplicates identical content',t=>{const db=memory(t);const a=archiveDocument(db,'who',base.url,{title:'A'},first);assert.equal(a,archiveDocument(db,'who',base.url,{title:'A'},later));assert.equal(db.prepare('SELECT count(*) n FROM documents').get().n,1);});
test('idempotent imports, revisions and a reverted correction remain auditable',t=>{const db=memory(t);assert.equal(appendObservation(db,base,null,first),1);assert.equal(appendObservation(db,base,null,later),0);assert.equal(appendObservation(db,{...base,metrics:{confirmed:9}},null,later),1);assert.equal(appendObservation(db,base,null,'2026-05-07T00:00:00.000Z'),1);assert.equal(observationHistory(db,1).length,3);});
test('valid time and knowledge time expose different revisions',t=>{const db=memory(t);appendObservation(db,base,null,first);appendObservation(db,{...base,metrics:{confirmed:9}},null,later);assert.equal(readDashboard(db,{at:'2026-05-02T23:59:59Z'}).observations[0].metrics.confirmed,9);assert.equal(readDashboard(db,{at:'2026-05-02T23:59:59Z',knownAt:first}).observations[0].metrics.confirmed,12);assert.equal(readDashboard(db,{at:first,knownAt:'2026-05-03T23:59:59Z'}).observations.length,0);});
test('a correction moving valid time outside selection does not resurrect old version',t=>{const db=memory(t);appendObservation(db,base,null,first);appendObservation(db,{...base,occurredAt:'2026-05-05T00:00:00Z'},null,later);assert.equal(readDashboard(db,{at:first}).observations.length,0);});
test('no future publications or unsafe links enter the archive',t=>{const db=memory(t);assert.throws(()=>appendObservation(db,base,null,'2026-05-01T00:00:00Z'),/future/);assert.throws(()=>appendObservation(db,{...base,url:'javascript:alert(1)'},null,first),/incomplète/);});
test('source lease excludes concurrent workers and expired leases recover',t=>{const db=memory(t),source=sources[0];const one=claimSource(db,source,first);assert.ok(one);assert.equal(claimSource(db,source,first,true),null);const two=claimSource(db,source,later);assert.ok(two);finishSource(db,source,one,2,null,later);assert.equal(db.prepare('SELECT lease_owner FROM source_state').get().lease_owner,two);finishSource(db,source,two,2,null,later);assert.equal(claimSource(db,source,later),null);});
test('failure preserves last success and retry backoff',t=>{const db=memory(t),s=sources[0];let id=claimSource(db,s,first);finishSource(db,s,id,1,null,first);id=claimSource(db,s,later);finishSource(db,s,id,0,'HTTP 503',later);const row=db.prepare('SELECT * FROM source_state').get();assert.equal(row.last_success,first);assert.equal(row.failures,1);assert.ok(row.next_attempt>later);});
test('territorial snapshots select latest valid version of each dataset',t=>{const db=memory(t);assert.equal(appendTerritory(db,snapshot,first),1);assert.equal(appendTerritory(db,snapshot,later),0);appendTerritory(db,{...snapshot,metadata:{...snapshot.metadata,validAt:'2026-05-05'},features:[]},later);assert.equal(readDashboard(db,{domain:'war',at:first}).territories[0].features.length,1);assert.equal(readDashboard(db,{domain:'war',at:later}).territories[0].features.length,0);assert.equal(readDashboard(db,{domain:'war',at:later,knownAt:first}).territories[0].features.length,1);});
test('territory import rejects unlicensed, malformed and future geometries',t=>{const db=memory(t);assert.throws(()=>appendTerritory(db,{...snapshot,metadata:{...snapshot.metadata,license:''}},first),/requis/);assert.throws(()=>appendTerritory(db,{...snapshot,features:[{...snapshot.features[0],geometry:{type:'Point',coordinates:[30,48]}}]},first),/Polygones/);assert.throws(()=>appendTerritory(db,{...snapshot,metadata:{...snapshot.metadata,validAt:'2099-01-01'}},first),/futur/);assert.throws(()=>appendTerritory(db,{...snapshot,features:[snapshot.features[0],snapshot.features[0]]},first),/unique/);});
test('territory batch failure rolls back all snapshots',t=>{const db=memory(t);assert.throws(()=>db.transaction(()=>{appendTerritory(db,snapshot,first);appendTerritory(db,{},first);})());assert.equal(db.prepare('SELECT count(*) n FROM territory_snapshots').get().n,0);});
test('RSS import is metadata-only and does not interpret numbers as cases',()=>{const xml='<rss><channel><item><title>Hantavirus bulletin</title><link>https://reliefweb.int/report/example</link><pubDate>Mon, 04 May 2026 12:00:00 GMT</pubDate><description>&lt;p&gt;197 contacts monitored&lt;/p&gt;</description><author>WHO</author></item></channel></rss>';const records=parseReliefWeb(xml,topics[0]);assert.equal(records.length,1);assert.equal(records[0].metrics,undefined);assert.equal(records[0].lat,null);assert.equal(records[0].summary.includes('197'),false);assert.throws(()=>parseReliefWeb('<html>Error</html>',topics[0]),/Invalid RSS feed/);});
test('network failure does not delete previous reports',async t=>{const db=memory(t);appendObservation(db,base,null,first);const result=await syncSources(db,{only:'who',force:true,get:async()=>{throw new Error('HTTP 503');}});assert.equal(result[0].status,'error');assert.ok(readDashboard(db).observations.some(o=>o.externalId==='bulletin'));});
test('successful source sync stores usable reports and is idempotent',async t=>{const db=memory(t);const get=async()=>JSON.stringify({value:[{Id:'don',Title:'Hantavirus report',UrlName:'2026-DON600',PublicationDate:'2026-05-04'}]});assert.equal((await syncSources(db,{only:'who',force:true,get}))[0].added,1);assert.equal((await syncSources(db,{only:'who',force:true,get}))[0].added,0);});
test('references never overwrite reviewed corrections',t=>{const db=memory(t);seedReferences(db);const o=readDashboard(db).observations.find(o=>o.topic==='hantavirus');appendObservation(db,{...o,title:'Correction reviewed'});seedReferences(db);assert.equal(readDashboard(db).observations.find(o=>o.topic==='hantavirus').title,'Correction reviewed');});
test('online backup restores committed WAL data',async()=>{const dir=mkdtempSync(join(tmpdir(),'omni-test-'));let db,restored;try{db=openStore(join(dir,'live.db'));appendObservation(db,base,null,first);await db.backup(join(dir,'backup.db'));restored=openStore(join(dir,'backup.db'));assert.equal(restored.pragma('integrity_check',{simple:true}),'ok');assert.equal(readDashboard(restored).observations.length,1);}finally{restored?.close();db?.close();rmSync(dir,{recursive:true,force:true});}});
test('VIINA extraction preserves dates, unknowns and localities changing control',async()=>{
  const {execFile}=await import('node:child_process');const {promisify}=await import('node:util');const {readFile}=await import('node:fs/promises');const run=promisify(execFile);
  const dir=mkdtempSync(join(tmpdir(),'omni-viina-test-'));
  try{
    const fixture=`import zipfile,json,pathlib,sys
p=pathlib.Path(sys.argv[1])
rows='geonameid,date,status,vcontrol_version\\n1,20260901,UA,20260908000000\\n2,20260901,NA,20260908000000\\n1,20260908,RU,20260908000000\\n2,20260908,NA,20260908000000\\n'
with zipfile.ZipFile(p/'control.zip','w') as z:z.writestr('control.csv',rows)
f={'type':'Feature','properties':{'geonameid':1,'name':'Synthetic fixture'},'geometry':{'type':'Polygon','coordinates':[[[30,48],[31,48],[31,49],[30,48]]]}}
(p/'places.geojson').write_text(json.dumps({'type':'FeatureCollection','features':[f]}))`;
    await run('python3',['-c',fixture,dir]);
    const {stdout}=await run('python3',['scripts/viina-extract.py',dir]);const result=JSON.parse(stdout);
    assert.equal(result.latest,'20260908');assert.equal(result.paths.length,2);
    const a=JSON.parse(await readFile(result.paths[0],'utf8')),b=JSON.parse(await readFile(result.paths[1],'utf8'));
    assert.equal(a.features.length,0);assert.equal(b.features.length,1);assert.equal(b.metadata.counts.UNKNOWN,1);assert.equal(b.metadata.changes.toRU,1);assert.equal(b.metadata.changes.fromRU,0);
  }finally{rmSync(dir,{recursive:true,force:true});}
});
