export const topics = [
  { id: 'hantavirus', domain: 'pandemic', name: 'Hantavirus', region: 'International', lat: null, lon: null, zoom: 2, description: 'Monitoring hantavirus bulletins and outbreaks. Treatment, residence and exposure locations are not interchangeable.' },
  { id: 'plague', domain: 'pandemic', name: 'Plague · monitoring', region: 'Irkutsk / worldwide', lat: 52.28, lon: 104.28, zoom: 5, description: 'Monitoring Yersinia pestis. The Irkutsk signal remains unconfirmed in the integrated references. A monitored contact is not a case.' },
  { id: 'ukraine', domain: 'war', name: 'Ukraine', region: 'Eastern Europe', country: 'Ukraine', lat: 48.5, lon: 34, zoom: 5 },
  { id: 'palestine', domain: 'war', name: 'Israel / Palestine', region: 'Middle East', country: 'occupied Palestinian territory', lat: 31.5, lon: 34.7, zoom: 7 },
  { id: 'iran-gulf', domain: 'war', name: 'Iran & Gulf', region: 'Persian Gulf / Strait of Hormuz', countries: ['Iran (Islamic Republic of)', 'Iraq', 'Kuwait', 'Bahrain', 'Qatar', 'Saudi Arabia', 'United Arab Emirates', 'Oman'], lat: 26.5, lon: 53.5, zoom: 5, description: 'Regional monitoring of Iran, Iraq and the Gulf states: reported hostilities, civilian impacts, diplomacy and maritime security around the Strait of Hormuz. Markers locate the theatre, not individual strikes. Reports and statements do not establish territorial control or verify claims by conflict parties.' },
  { id: 'sudan', domain: 'war', name: 'Sudan', region: 'Eastern Africa', country: 'Sudan', lat: 15.5, lon: 30, zoom: 5 },
  { id: 'myanmar', domain: 'war', name: 'Myanmar', region: 'Southeast Asia', country: 'Myanmar', lat: 21, lon: 96, zoom: 5 },
  { id: 'syria', domain: 'war', name: 'Syria', region: 'Middle East', country: 'Syrian Arab Republic', lat: 35, lon: 38, zoom: 6 },
  { id: 'yemen', domain: 'war', name: 'Yemen', region: 'Arabian Peninsula', country: 'Yemen', lat: 15.5, lon: 47, zoom: 5 },
  { id: 'drc', domain: 'war', name: 'DR Congo', region: 'Central Africa', country: 'Democratic Republic of the Congo', lat: -2.5, lon: 28, zoom: 5 },
];

export const sources = [
  { id:'social-iran-gulf',name:'Exa · Iran & Gulf social posts and videos',domain:'war',topic:'iran-gulf',kind:'discovery',url:'https://exa.ai',interval:10800,license:'Original authors retain rights; short excerpts and source links',description:'Every three hours: English, Arabic and Persian social searches and video discovery. Only dated individual posts are archived. Coverage depends on indexing and is not a live platform feed. All results remain unverified signals. Shares the Gulf daily Exa budget.',connector:'social-exa' },
  { id:'exa-iran-gulf',name:'Exa · Iran & Gulf news discovery',domain:'war',topic:'iran-gulf',kind:'discovery',url:'https://exa.ai',interval:3600,license:'Original publishers retain rights; metadata and links only',description:'Four hourly searches: maritime security, hostilities, diplomacy and humanitarian impacts. Undated results are excluded. Search results are reports, not verified events.',connector:'exa' },
  { id:'ukmto-iran-gulf',name:'UKMTO · official documents via Exa',domain:'war',topic:'iran-gulf',kind:'official',url:'https://www.ukmto.org/ukmto-products',interval:3600,license:'Crown copyright; official document links and metadata',description:'Official UKMTO PDFs discovered through Exa because direct collection is unavailable. Issue dates and explicitly labelled report times are retained. No exact incident coordinates are inferred.',connector:'ukmto-exa' },
  { id:'portwatch-hormuz',name:'IMF PortWatch · Strait of Hormuz',domain:'war',topic:'iran-gulf',kind:'indicator',url:'https://portwatch.imf.org/',interval:21600,license:'IMF terms of use · https://www.imf.org/external/terms.htm',description:'Daily AIS-derived vessel transit estimates. The latest 120 source observations are refreshed every six hours and revisions are archived. Source data may lag; non-broadcasting vessels may be absent.',connector:'portwatch' },
  { id: 'un-news-iran-gulf', name: 'UN News · Iran & Gulf', domain: 'war', kind: 'official', topic: 'iran-gulf', url: 'https://news.un.org/en/', feedUrl: 'https://news.un.org/feed/subscribe/en/news/region/middle-east/feed/rss.xml', interval: 3600, license: 'UN terms; bibliographic metadata and links only', description: 'English UN News regional feed, filtered for Iran and Gulf security. Statements remain attributed reports. The feed is a rolling publication window, not an exhaustive incident log.', connector: 'un-news' },
  { id: 'viina', name: 'VIINA 2.0 · Ukraine', domain: 'war', kind: 'assessment', topic: 'ukraine', url: 'https://github.com/zhukovyuri/VIINA', interval: 86400, license: 'ODbL 1.0 · Yuri Zhukov & Natalie Ayers', description: 'Majority assessments of locality control, projected onto GeoNames cells. Latest, 7-day and 30-day snapshots archived; these are not precise military boundaries.', connector: 'viina' },
  { id: 'who', name: 'WHO · Disease Outbreak News', domain: 'pandemic', kind: 'official', url: 'https://www.who.int/emergencies/disease-outbreak-news', interval: 3600, license: 'WHO terms; links and metadata', description: 'Official bulletins. Publication does not imply that all reported cases are confirmed.', connector: 'who' },
  { id: 'datagouv-hanta', name: 'data.gouv · Hantavirus 2026', domain: 'pandemic', kind: 'community', url: 'https://www.data.gouv.fr/datasets/hantavirus-2026', interval: 86400, license: 'Open Licence 2.0 (as declared in the catalogue)', description: 'Ludwig Boudeweel, independent contributor. Catalogue monitored; the case-count API returned HTTP 500 during integration. No counts imported from this API.', connector: 'datagouv' },
  { id: 'editorial', name: 'References checked at integration', domain: 'pandemic', kind: 'curated', url: 'https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON611', interval: 0, license: 'Original summaries with attribution', description: 'Historical records entered from the cited references. This dataset is not a news feed.', connector: null },
  ...topics.map(t => ({ id: `reliefweb-${t.id}`, name: `ReliefWeb · ${t.name}`, domain: t.domain, topic: t.id, kind: 'aggregator', url: 'https://reliefweb.int/updates', interval: 3600, license: 'Original publishers retain rights; titles and links only', description: 'Humanitarian publications. Markers indicate theatres, not incident locations.', connector: 'reliefweb' })),
  { id: 'territories', name: 'Licensed territorial snapshots', domain: 'war', kind: 'assessment', url: 'https://acleddata.com/methodology/mapping-territorial-control-and-contestation-syria', interval: 21600, license: 'Licence and attribution required for each snapshot', description: 'Manual import of dated GeoJSON snapshots or an optional licensed feed. No frontlines inferred from articles.', connector: 'territories' },
];

export const referenceObservations = [
  { sourceId: 'editorial', externalId: 'who-hondius-2026-07-02', domain: 'pandemic', topic: 'hantavirus', kind: 'assessment', title: 'MV Hondius: outbreak contained according to WHO', summary: 'The WHO bulletin of 2 July describes interrupted transmission following contact monitoring. This historical count does not cover all hantavirus infections worldwide.', url: 'https://www.who.int/emergencies/disease-outbreak-news/item/2026-DON611', occurredAt: '2026-07-02T00:00:00Z', publishedAt: '2026-07-02T00:00:00Z', status: 'contained', location: 'International outbreak · MV Hondius', lat: null, lon: null, metrics: { confirmed: 12, probable: 1, deaths: 3, scope: 'MV Hondius outbreak', basis: 'cumulative', unit: 'people', asOf: '2026-07-02' }, publisher: 'World Health Organization', precision: 'multi-country' },
  { sourceId: 'editorial', externalId: 'irkutsk-signal-2026-10-04', domain: 'pandemic', topic: 'plague', kind: 'signal', title: 'Irkutsk: unverified health signal', summary: 'An article dated 4 October reports a death and suspected plague, with pneumonia of unknown origin announced. Plague is not confirmed in the integrated references. No confirmed case count is assigned.', url: 'https://www.euronews.com/2026/10/04/has-plague-returned-to-siberia-panic-in-russia-after-death-of-lab-worker', occurredAt: '2026-10-02T00:00:00Z', publishedAt: '2026-10-04T15:07:00Z', status: 'unverified', location: 'Irkutsk region · regional marker', lat: 52.28, lon: 104.28, publisher: 'Euronews (secondary source)', precision: 'region' },
];
