// Presentation translations only: archived evidence and checksums remain unchanged.
const labels = new Map(Object.entries({
  "Suivi des bulletins et épisodes liés aux hantavirus. Les localisations de soins, de résidence et d’exposition ne sont pas interchangeables.": "Monitoring hantavirus bulletins and outbreaks. Treatment, residence and exposure locations are not interchangeable.",
  "Peste · veille": "Plague · monitoring",
  "Irkoutsk / monde": "Irkutsk / worldwide",
  "Veille sur Yersinia pestis. Le signal d’Irkoutsk reste non confirmé dans les références intégrées. Un contact surveillé ne constitue pas un cas.": "Monitoring Yersinia pestis. The Irkutsk signal remains unconfirmed in the integrated references. A monitored contact is not a case.",
  "Europe orientale": "Eastern Europe",
  "Israël / Palestine": "Israel / Palestine",
  "Proche-Orient": "Middle East",
  "Soudan": "Sudan",
  "Afrique orientale": "Eastern Africa",
  "Asie du Sud-Est": "Southeast Asia",
  "Syrie": "Syria",
  "Yémen": "Yemen",
  "Péninsule arabique": "Arabian Peninsula",
  "RD Congo": "DR Congo",
  "Afrique centrale": "Central Africa",
  "Évaluations majoritaires du contrôle des localités, projetées sur des cellules GeoNames. Dernier relevé, J−7 et J−30 archivés ; ce ne sont pas des frontières militaires précises.": "Majority assessments of locality control, projected onto GeoNames cells. Latest, 7-day and 30-day snapshots archived; these are not precise military boundaries.",
  "OMS · Disease Outbreak News": "WHO · Disease Outbreak News",
  "Conditions OMS ; liens et métadonnées": "WHO terms; links and metadata",
  "Bulletins officiels. Une publication ne signifie pas que tous ses cas sont confirmés.": "Official bulletins. Publication does not imply that all reported cases are confirmed.",
  "Licence ouverte 2.0 (déclarée au catalogue)": "Open Licence 2.0 (as declared in the catalogue)",
  "Ludwig Boudeweel, contributeur indépendant. Catalogue surveillé ; API de chiffres en erreur 500 lors de l’intégration. Aucun bilan importé de cette API.": "Ludwig Boudeweel, independent contributor. Catalogue monitored; the case-count API returned HTTP 500 during integration. No counts imported from this API.",
  "Références vérifiées à l’intégration": "References checked at integration",
  "Synthèses originales avec attribution": "Original summaries with attribution",
  "Repères historiques saisis depuis les références citées. Ce jeu n’est pas un flux d’actualité.": "Historical records entered from the cited references. This dataset is not a news feed.",
  "Droits des éditeurs d’origine ; titres et liens uniquement": "Original publishers retain rights; titles and links only",
  "Publications humanitaires. Les marqueurs sont des repères de théâtre, pas la localisation des incidents.": "Humanitarian publications. Markers indicate theatres, not incident locations.",
  "Relevés territoriaux autorisés": "Licensed territorial snapshots",
  "Licence et attribution exigées pour chaque relevé": "Licence and attribution required for each snapshot",
  "Import manuel de relevés GeoJSON datés ou flux autorisé facultatif. Aucune ligne de front déduite des articles.": "Manual import of dated GeoJSON snapshots or an optional licensed feed. No frontlines inferred from articles.",
  "MV Hondius : épisode contenu selon l’OMS": "MV Hondius: outbreak contained according to WHO",
  "Le bulletin OMS du 2 juillet décrit l’interruption de la transmission après le suivi des contacts. Ce bilan historique ne décrit pas l’ensemble des infections à hantavirus dans le monde.": "The WHO bulletin of 2 July describes interrupted transmission following contact monitoring. This historical count does not cover all hantavirus infections worldwide.",
  "Épisode international · MV Hondius": "International outbreak · MV Hondius",
  "Épisode MV Hondius": "MV Hondius outbreak",
  "personnes": "people",
  "Organisation mondiale de la Santé": "World Health Organization",
  "Irkoutsk : signal sanitaire à vérifier": "Irkutsk: unverified health signal",
  "Un article du 4 octobre rapporte un décès et une suspicion de peste, avec une pneumonie d’origine inconnue annoncée. La confirmation de peste n’est pas établie dans les références intégrées. Aucun nombre de cas confirmés n’est attribué.": "An article dated 4 October reports a death and suspected plague, with pneumonia of unknown origin announced. Plague is not confirmed in the integrated references. No confirmed case count is assigned.",
  "Région d’Irkoutsk · repère régional": "Irkutsk region · regional marker",
  "Euronews (source secondaire)": "Euronews (secondary source)",
  "Publication référencée par ReliefWeb. Consulter la source pour son contenu, la période couverte et sa méthodologie. La date affichée est celle de publication.": "Publication indexed by ReliefWeb. Consult the source for content, coverage period and methodology. The displayed date is the publication date.",
  "Éditeur référencé par ReliefWeb": "Publisher indexed by ReliefWeb",
  "Bulletin officiel de l’OMS. Les chiffres et les lieux sont à lire dans le document ; aucune extraction automatique de cas individuels.": "Official WHO bulletin. Read the document for figures and locations; individual cases are not automatically extracted.",
  "Voir le bulletin OMS": "See WHO bulletin",
  "Réponse trop volumineuse": "Response too large",
  "Réponse OMS vide ou format inattendu": "Empty WHO response or unexpected format",
  "Métadonnées data.gouv invalides": "Invalid data.gouv metadata",
  "Catalogue accessible ; ressource Hantavirus signalée indisponible par data.gouv. Aucun bilan importé.": "Catalogue accessible; data.gouv reports the Hantavirus resource as unavailable. No counts imported.",
  "Aucun flux territorial autorisé configuré. Import GeoJSON disponible.": "No licensed territory feed configured. GeoJSON import available.",
  "Contrôle russe évalué": "Assessed Russian control",
  "Contrôle contesté": "Contested control",
  "ODbL 1.0 · base dérivée OMNI sous ODbL 1.0": "ODbL 1.0 · OMNI derived database under ODbL 1.0",
  "Statut majoritaire VIINA (Wikipedia, Wikipedia enrichi, DeepStateMap), projeté sur les cellules de localités GeoNames. Géométries arrondies à 5 décimales. Cellules RU et contestées seulement ; absence de cellule affichée ne signifie pas contrôle ukrainien. Ce ne sont pas des frontières militaires précises.": "VIINA majority status (Wikipedia, enriched Wikipedia, DeepStateMap), projected onto GeoNames locality cells. Geometry rounded to 5 decimal places. RU and contested cells only; an absent cell does not imply Ukrainian control. These are not precise military boundaries.",
  "Collecte interrompue ; bail expiré": "Collection interrupted; lease expired",
  "Panneau ou sujet invalide": "Invalid panel or topic",
  "Date ISO invalide": "Invalid ISO date",
  "Identifiant invalide": "Invalid identifier",
  "Relevé introuvable": "Snapshot not found"
}));
export function englishPresentation(value) {
  if (typeof value === 'string') return labels.get(value) ?? value;
  if (Array.isArray(value)) return value.map(englishPresentation);
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, englishPresentation(entry)]));
  return value;
}
