export type Domain = 'global' | 'pandemic' | 'war';
export type Topic = {id:string;domain:string;name:string;region:string;lat:number|null;lon:number|null;zoom:number;description?:string};
export type Observation = {id:number;sourceId:string;externalId:string;domain:string;topic:string;kind:string;title:string;summary:string;url:string;occurredAt:string;publishedAt:string;recordedAt:string;status:string;location:string;lat:number|null;lon:number|null;precision:string;publisher:string;revisions:number;feedType?:string;platform?:string;author?:string|null;excerpt?:string;image?:string|null;category?:string;dateBasis?:string;reportedAt?:string|null;reference?:string|null;discoveredVia?:string;metrics?:{confirmed?:number;probable?:number;deaths?:number;scope:string;basis:string;unit:string;asOf:string}};
export type Source = {id:string;name:string;domain:string;topic?:string;kind:string;url:string;description:string;license:string;health:string;lastDataAt?:string;last_attempt?:string;last_success?:string;error?:string};
export type Territory = {type:'FeatureCollection';features:GeoJSON.Feature[];metadata:{topic:string;datasetId:string;publisher:string;sourceUrl:string;license:string;validAt:string;method?:string;counts?:Record<string,number>;changes?:{since:string;toRU:number;fromRU:number;changed:number}};recordedAt:string;snapshotId:number};
export type Traffic = {series:string;sourceUrl:string;publisher:string;unit:string;method:string;points:{date:string;total:number|null;tankers:number|null;cargo:number|null;recordedAt:string}[]};
export type DashboardData = {traffic?:Traffic|null;discoveryBudget?:{day:string;requests:number;actualUsd:number;budgetUsedUsd:number;limitUsd:number};observations:Observation[];sources:Source[];topics:Topic[];territories:Territory[];timeline:string[];truncated:boolean;fetchedAt:string;at:string;knownAt:string;runs:{id:string;source_id:string;started_at:string;status:string;added:number;error?:string}[]};
export const statusLabels:Record<string,string> = {contained:'Contained outbreak',unverified:'Unverified',reported:'Publication',confirmed:'Confirmed',retracted:'Retracted',controlled:'Assessed control',contested:'Contested area',claimed:'Claim'};
export const dateLabel = (v?:string) => v ? new Date(v).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}) : '—';

export const feedType = (o:Observation) => o.feedType || (['ukmto-iran-gulf','un-news-iran-gulf'].includes(o.sourceId)?'official':'news');
